version: "3"

networks:
    project-network:
        driver: bridge

services:
    database:
        image: "postgres:latest"
        restart: always
        container_name: speakup_database
        environment:
            POSTGRES_PASSWORD: secret
        ports:
            - "5437:5432"
    cache:
        image: "redis:6.2-alpine"
        restart: always
        container_name: speakup_cache
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVXf2xKPCDg543oLd2t245281
    clickhouse:
        image: "bitnami/clickhouse:latest"
        restart: always
        container_name: speakup_clickhouse
        environment:
            CLICKHOUSE_ADMIN_USER: "admin"
            CLICKHOUSE_ADMIN_PASSWORD: "admin"
            CLICKHOUSE_TCP_PORT: 9000
            CLICKHOUSE_HTTP_PORT: 8123
        ports:
            - "9001:9000"
            - "8123:8123"